services:
  dev:
    hostname: api_page_dev
    container_name: api_page_dev
    build:
      context: .
      dockerfile: docker/development.dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - valkey
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: ["air"]
  prod:
    hostname: api_page_prod
    container_name: api_page_prod
    build:
      context: .
      dockerfile: docker/production.dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/build
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: ["/api"]
  valkey:
    container_name: api_page_valkey
    hostname: api_page_valkey
    build:
      context: .
      dockerfile: docker/valkey.dockerfile
    volumes:
      - ./docker/scripts/valkey.conf:/usr/local/etc/valkey/valkey.conf
      - ./data:/data
    command: sh -c "/usr/local/etc/valkey/valkey.sh"
    # Run as privileged to allow the container to change the vm.overcommit_memory setting.
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"